name: mywiki

services:
  quote:
    image: robinlant/mywiki-quotes:1
    environment:
      - ADDR=:8081
    restart: on-failure:3
    networks:
      - quote-net

  wiki:
    image: robinlant/mywiki-wiki:1
    ports:
      - 8800:8800
    restart: on-failure:3
    environment:
      - ADDR=:8800
      - MONGO_CON=mongodb://mongo:27017
      - MONGO_DB=wiki
      - QUOTES_URL=http://quote:8081
    networks:
      - mongo-net
      - quote-net
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2
    networks:
      - mongo-net

networks:
  quote-net:
  mongo-net:
