name: mywiki

services:
  proxy:
    image: robinlant/mywiki-proxy:latest
    ports:
      - 8080:80
    networks:
      back-net:
        aliases:
          - quotes

  quotes-1:
    image: robinlant/mywiki-quotes:latest
    environment:
      - ADDR=:8000
    restart: on-failure:3
    networks:
      - back-net

  quotes-2:
    image: robinlant/mywiki-quotes:latest
    environment:
      - ADDR=:8000
    restart: on-failure:3
    networks:
      - back-net

  wiki-1:
    image: robinlant/mywiki-wiki:latest
    restart: on-failure:3
    environment:
      - ADDR=:8000
      - MONGO_CON=mongodb://mongo:27017
      - MONGO_DB=wiki
      - QUOTES_URL=http://quotes
    networks:
      - mongo-net
      - back-net
    depends_on:
      - mongo

  wiki-2:
    image: robinlant/mywiki-wiki:latest
    restart: on-failure:3
    environment:
      - ADDR=:8000
      - MONGO_CON=mongodb://mongo:27017
      - MONGO_DB=wiki
      - QUOTES_URL=http://quotes
    networks:
      - mongo-net
      - back-net
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2
    networks:
      - mongo-net
    volumes:
      - mongo:/data/db

networks:
  back-net:
  mongo-net:

volumes:
  mongo:
