{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  defaultBackend:
    service:
      name: {{ .Values.appName }}-wiki
      port:
        number: {{ .Values.wiki.port }}
  rules:
  {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-wiki
                port:
                  number: {{ .Values.wiki.port }}
  {{- end }}
{{- end }}
