apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-wiki
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-wiki
spec:
  replicas: {{ .Values.wiki.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-wiki
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-wiki
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: wiki
        image: {{ .Values.wiki.image }}
        env:
        {{- range $key, $val := .Values.wiki.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- if not (hasKey .Values.wiki.env "MONGO_CON") }}
        - name: MONGO_CON
          value: "mongodb://{{ .Values.appName }}-mongo:{{ .Values.mongo.port }}"
        {{- end }}
        {{- if not (hasKey .Values.wiki.env "QUOTES_URL") }}
        - name: QUOTES_URL
          value: "http://{{ .Values.appName }}-quotes:{{ .Values.quotes.port }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.wiki.port }}
        resources:
          {{- toYaml .Values.wiki.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-wiki
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}-wiki
  ports:
  - port: {{ .Values.wiki.port }}
    targetPort: {{ .Values.wiki.port }}
