apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mongo.persistance.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongo.persistance.hostPath }}
  persistentVolumeReclaimPolicy: {{ .Values.mongo.persistance.recailmPolicy }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.persistance.storage }}
