apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  namespace: maksym
spec:
  ingressClassName: nginx-ic
  defaultBackend:
    service:
      name: wiki
      port:
        number: 8000
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-ic
spec:
  controller:  k8s.io/ingress-nginx

