apiVersion: v2
name: mywiki
description: mywiki
type: application
version: 0.2.1
appVersion: "n/a"

dependencies:
  - name: ingress-nginx
    version: 4.14.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
