appName: wiki
namespace: default

imagePullSecrets:
  - name: docker-creds

wiki:
  image: robinlant/mywiki-wiki:main.0d2be
  replicas: 2
  port: 8000
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "250m"
      memory: "500Mi"
  env:
    ADDR: ":8000"

quotes:
  image: robinlant/mywiki-quotes:latest
  replicas: 2
  port: 8000
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "150m"
      memory: "250Mi"
  env:
    ADDR: ":8000"

mongo:
  image: mongo:8.2
  port: 27017
  persistence:
    enabled: false
  resources:
    requests:
      cpu: "80m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "800Mi"

ingress:
  enabled: false
  className: nginx
  host: ""
  path:
    defaultBackend: true
    path: "/wiki"
    type: "Prefix"

ingress-nginx:
  enabled: false
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
