name: Build and push images
on:
  push:

jobs:
  build-push:
    strategy:
      matrix:
        microservice:
          - wiki
          - quotes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changes:
              - '${{ matrix.microservice }}/**'
      - name: Login into Dockerhub
        if: steps.changes.outputs.changes == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: QEMU setup
        if: steps.changes.outputs.changes == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Buildx setup
        if: steps.changes.outputs.changes == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Get short github.sha
        if: steps.changes.outputs.changes == 'true'
        id: short_sha
        run: |
          echo "sha_short=$(echo $GITHUB_SHA | cut -c1-5)" >> $GITHUB_OUTPUT
      - name: Build and push ${{ matrix.microservice }}
        if: steps.changes.outputs.changes == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.microservice }}
          push: true
          tags: ${{github.repository}}-${{ matrix.microservice }}:${{github.ref_name}}+${{steps.short_sha.outputs.sha_short}}
