name: Build and push images
on:
  push:

jobs:
  build-push:
    strategy:
      matrix:
        microservice:
          - wiki
          - quotes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        with:
          filters: |
            ${{ matrix.microservice }}:
              - '${{ matrix.microservice }}/**'
      - name: Login into Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: QEMU setup
        uses: docker/setup-qemu-action@v3
      - name: Buildx setup
        uses: docker/setup-buildx-action@v3
      - name: Build and push ${{ matrix.microservice }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.microservice }}
          push: true
          tags: ${{github.repository}}-${{ matrix.microservice }}:latest

